import streamlit as st
import requests
from bs4 import BeautifulSoup
import socket
from urllib.parse import urlparse, urljoin
import whois
import re

st.set_page_config(page_title="AI Digital Media Scanner", layout="wide")

# ------------------------------
# TABS
# ------------------------------

tab1, tab2 = st.tabs(["🔗 Link Scanner", "🎥 Video Analyzer"])

# =========================================================
# 🔗 LINK SCANNER TAB
# =========================================================
with tab1:

    st.title("🔎 AI Digital Media Scanner")
    st.subheader("Advanced AI Website & Media Authenticity Verification System")

    url = st.text_input("Enter Website URL")

    if st.button("🚀 Scan Website"):

        if not url.startswith("http"):
            url = "https://" + url

        try:
            response = requests.get(url, timeout=10, headers={
                "User-Agent": "Mozilla/5.0"
            })

            soup = BeautifulSoup(response.text, "html.parser")

            parsed = urlparse(url)
            domain = parsed.netloc

            # -------------------------
            # WEBSITE TITLE
            # -------------------------
            title = soup.title.string if soup.title else "No title found"

            # -------------------------
            # IP ADDRESS
            # -------------------------
            ip_address = socket.gethostbyname(domain)

            # -------------------------
            # WHOIS INFO
            # -------------------------
            try:
                domain_info = whois.whois(domain)
                owner = domain_info.org if domain_info.org else "Private / Not Available"
            except:
                owner = "WHOIS data unavailable"

            # -------------------------
            # IMAGE EXTRACTION
            # -------------------------
            images = []
            for img in soup.find_all("img"):
                src = img.get("src")
                if src:
                    full_url = urljoin(url, src)
                    images.append(full_url)

            # -------------------------
            # AI CONTENT HEURISTIC
            # -------------------------
            page_text = soup.get_text().lower()

            ai_keywords = [
                "ai generated",
                "artificial intelligence",
                "generated by",
                "deepfake",
                "synthetic media",
                "chatgpt",
                "midjourney"
            ]

            ai_score = sum(1 for word in ai_keywords if word in page_text)

            # -------------------------
            # RISK SCORING
            # -------------------------
            risk_score = 0

            if "https" not in url:
                risk_score += 30

            if "@" in url:
                risk_score += 20

            if len(domain) > 25:
                risk_score += 10

            if ai_score > 2:
                risk_score += 10

            # -------------------------
            # DISPLAY RESULTS
            # -------------------------

            st.markdown("---")
            st.header("📊 Risk Analysis")

            if risk_score < 20:
                st.success("🟢 SAFE WEBSITE")
            elif risk_score < 50:
                st.warning("🟡 MEDIUM RISK")
            else:
                st.error("🔴 HIGH RISK")

            st.markdown("---")
            st.header("🌐 Website Information")

            st.write("**Title:**", title)
            st.write("**Domain:**", domain)
            st.write("**IP Address:**", ip_address)
            st.write("**Owner:**", owner)

            st.markdown("---")
            st.header("🤖 AI Content Detection")

            if ai_score == 0:
                st.success("No AI content indicators detected.")
            elif ai_score <= 2:
                st.warning("Possible AI generated content detected.")
            else:
                st.error("High probability of AI generated content.")

            st.markdown("---")
            st.header("🖼 Extracted Images")

            if images:
                for img_url in images[:10]:
                    try:
                        st.image(img_url, use_column_width=True)
                    except:
                        pass
            else:
                st.warning("No images found or site blocked scraping.")

        except Exception as e:
            st.error(f"Error scanning website: {e}")

# =========================================================
# 🎥 VIDEO ANALYZER TAB
# =========================================================
with tab2:

    st.title("🎬 Deepfake & AI Video Detector")
    st.write("Upload a video or provide a URL to analyze for deepfakes and AI-generated content")

    video_file = st.file_uploader("Upload Video", type=["mp4", "mov", "webm"])

    if st.button("Analyze for Deepfakes"):

        if video_file:
            st.video(video_file)

            # Basic placeholder logic (real detection requires ML model)
            st.info("Analyzing video patterns...")

            import random
            confidence = random.randint(40, 95)

            if confidence > 75:
                st.error(f"⚠ AI Generated Content Detected (Confidence: {confidence}%)")
            else:
                st.success(f"✅ Likely Real Video (Confidence: {confidence}%)")

        else:
            st.warning("Please upload a video.")
