import streamlit as st
import requests
from bs4 import BeautifulSoup
import socket
from urllib.parse import urlparse, urljoin
import re

st.set_page_config(page_title="AI Digital Risk Scanner", layout="centered")

st.title("🔍 AI Digital Media Forensic Scanner")
st.markdown("---")

url = st.text_input("Enter Website URL")

scan = st.button("🚀 Scan Website", use_container_width=True)

if scan:

    if not url:
        st.warning("Please enter a website URL")
        st.stop()

    if not url.startswith("http"):
        url = "https://" + url

    with st.spinner("Analyzing website..."):

        try:
            headers = {"User-Agent": "Mozilla/5.0"}
            response = requests.get(url, headers=headers, timeout=10)
            soup = BeautifulSoup(response.text, "html.parser")

            parsed = urlparse(url)
            domain = parsed.netloc

            # -----------------------
            # IP ADDRESS
            # -----------------------
            try:
                ip_address = socket.gethostbyname(domain)
            except:
                ip_address = "Unable to fetch"

            st.markdown("## 🌐 Website Information")
            st.write("**Domain:**", domain)
            st.write("**IP Address:**", ip_address)

            if soup.title:
                st.write("**Title:**", soup.title.string)

            # -----------------------
            # RISK ANALYSIS
            # -----------------------
            risk_score = 0

            if "http://" in url:
                risk_score += 2

            if len(domain) > 30:
                risk_score += 1

            if domain.count("-") > 2:
                risk_score += 1

            if response.status_code != 200:
                risk_score += 2

            st.markdown("## 🚨 Risk Analysis")

            if risk_score >= 4:
                st.error("🔴 HIGH RISK WEBSITE")
            elif risk_score >= 2:
                st.warning("🟡 MEDIUM RISK WEBSITE")
            else:
                st.success("🟢 SAFE WEBSITE")

            # -----------------------
            # AI CONTENT DETECTION
            # -----------------------
            st.markdown("## 🤖 AI Content Detection")

            page_text = soup.get_text().lower()

            ai_keywords = [
                "ai generated",
                "chatgpt",
                "artificial intelligence",
                "generated by ai",
                "deepfake",
                "machine learning model"
            ]

            ai_found = False
            keyword_hits = 0

            for word in ai_keywords:
                if word in page_text:
                    ai_found = True
                    keyword_hits += 1

            sentences = re.split(r'[.!?]', page_text)
            long_sentences = sum(1 for s in sentences if len(s.split()) > 25)

            if long_sentences > 40:
                ai_found = True

            if ai_found:
                st.warning(f"⚠️ Possible AI Generated Content Detected ({keyword_hits} indicators found)")
            else:
                st.success("No Strong AI Content Indicators Found")

            # -----------------------
            # IMAGE DISPLAY
            # -----------------------
            st.markdown("## 🖼 Image Analysis")

            images = soup.find_all("img")
            st.write("Total Images Found:", len(images))

            displayed = 0

            for img in images:
                src = img.get("src")
                if src:
                    full_url = urljoin(url, src)

                    try:
                        st.image(full_url, width=300)
                        displayed += 1
                    except:
                        pass

                    if displayed == 5:
                        break

            if displayed == 0:
                st.info("No displayable images found or site blocks image loading.")

            # -----------------------
            # PAGE SUMMARY
            # -----------------------
            st.markdown("## 📊 Page Summary")

            links = soup.find_all("a", href=True)
            st.write("Total Links Found:", len(links))

        except Exception:
            st.error("🔴 Unable to Scan Website")
