import streamlit as st
import requests
from bs4 import BeautifulSoup
import socket
from urllib.parse import urlparse
import re

st.set_page_config(page_title="AI Digital Risk Scanner", layout="centered")

st.title("🔍 AI Digital Media Forensic Scanner")
st.markdown("---")

url = st.text_input("Enter Website URL")

scan = st.button("🚀 Scan Website", use_container_width=True)

if scan:

    if not url:
        st.warning("Please enter a website URL")
        st.stop()

    if not url.startswith("http"):
        url = "https://" + url

    with st.spinner("Analyzing website..."):

        try:
            headers = {
                "User-Agent": "Mozilla/5.0"
            }

            response = requests.get(url, headers=headers, timeout=10)
            soup = BeautifulSoup(response.text, "html.parser")

            parsed_url = urlparse(url)
            domain = parsed_url.netloc

            try:
                ip_address = socket.gethostbyname(domain)
            except:
                ip_address = "Unable to fetch"

            st.markdown("---")
            st.markdown("## 🌐 Website Information")
            st.write("**Domain:**", domain)
            st.write("**IP Address:**", ip_address)

            if soup.title:
                st.write("**Title:**", soup.title.string)

            # -------------------------
            # RISK FACTOR ANALYSIS
            # -------------------------
            risk_score = 0

            if "http://" in url:
                risk_score += 2

            if len(domain) > 30:
                risk_score += 1

            if domain.count("-") > 2:
                risk_score += 1

            if response.status_code != 200:
                risk_score += 2

            st.markdown("## 🚨 Risk Analysis")

            if risk_score >= 3:
                st.error("🔴 RISKY WEBSITE")
            else:
                st.success("🟢 SAFE WEBSITE")

            # -------------------------
            # AI CONTENT DETECTION
            # -------------------------
            st.markdown("## 🤖 AI Content Detection")

            page_text = soup.get_text().lower()

            ai_keywords = [
                "ai generated",
                "chatgpt",
                "artificial intelligence",
                "generated by ai",
                "deepfake",
                "machine learning model"
            ]

            ai_found = False

            for keyword in ai_keywords:
                if keyword in page_text:
                    ai_found = True
                    break

            sentences = re.split(r'[.!?]', page_text)
            if len(sentences) > 100:
                repetitive = sum(1 for s in sentences if len(s.split()) > 25)
                if repetitive > 30:
                    ai_found = True

            if ai_found:
                st.warning("⚠️ Possible AI Generated Content Detected")
            else:
                st.success("No Strong AI Content Indicators Found")

            # -------------------------
            # PAGE SUMMARY
            # -------------------------
            st.markdown("## 📊 Page Summary")

            links = soup.find_all("a", href=True)
            images = soup.find_all("img")

            st.write("Total Links Found:", len(links))
            st.write("Total Images Found:", len(images))

        except Exception:
            st.error("🔴 Unable to Scan Website")
